# Generated by Django 2.0.2 on 2018-03-14 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180314_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='username',
            field=models.CharField(default='babyD', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_post_title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 14, 22, 16, 13, 775485, tzinfo=utc)),
        ),
    ]
