# Generated by Django 2.0.3 on 2018-03-15 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180314_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateField(default=datetime.date(2018, 3, 15), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.date(2018, 3, 15)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 15, 7, 45, 29, 654366, tzinfo=utc)),
        ),
    ]
