# Generated by Django 2.0.3 on 2018-03-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180315_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
