# Generated by Django 2.0.3 on 2018-03-19 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180319_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_date', '-post_time']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_time',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
